[package]
name = "zed-wasm"
version = "0.2.0"
description = "Zed extension of WebAssembly Language Tools."
authors = ["Pig Fang <g-plane@hotmail.com>"]
license = "MIT"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7.0"
