id = "wat"
name = "WebAssembly Text Format"
version = "0.2.0"
schema_version = 1
authors = ["Pig Fang <g-plane@hotmail.com>"]
description = "Language support of WebAssembly Text Format"
repository = "https://github.com/g-plane/zed-wasm"

[grammars.wat]
repository = "https://github.com/g-plane/tree-sitter-wat"
commit = "20d139ef7133257bdebec52711c7cbb388bd4092"

[language_servers.wasm-language-tools]
name = "WebAssembly Language Tools"
language = "WebAssembly Text Format"
