id = "wat"
name = "WebAssembly Text Format"
version = "0.2.0"
schema_version = 1
authors = ["Pig Fang <g-plane@hotmail.com>"]
description = "Language support of WebAssembly Text Format"
repository = "https://github.com/g-plane/zed-wasm"

[grammars.wat]
repository = "https://github.com/g-plane/tree-sitter-wat"
commit = "5a63669d9dd8eba5318801a5c1b3fbea6ccf6102"

[language_servers.wasm-language-tools]
name = "WebAssembly Language Tools"
language = "WebAssembly Text Format"
