id = "wat"
name = "WebAssembly Text Format"
version = "0.2.2"
schema_version = 1
authors = ["Pig Fang <g-plane@hotmail.com>"]
description = "Language support of WebAssembly Text Format"
repository = "https://github.com/g-plane/zed-wasm"

[grammars.wat]
repository = "https://github.com/g-plane/tree-sitter-wat"
commit = "72125dd36b1361757d15fd2f495206bf6a6de454"

[language_servers.wasm-language-tools]
name = "WebAssembly Language Tools"
language = "WebAssembly Text Format"
